# Author: Francisco Gutierrez
# Email: francisco.gutierrez@globallogic.com
# Date: 2025-03-05
# Description: This workflow file automates the image build and deployment process for MS-APPDATA PROD, into GCP Artifact Registry
# This workflow file will be triggered by an approved pull request or an emergency bypassed merge just allowed to admin users from @CodeOwners GitHub team.

name: ms-appdata deploy container image into GCP Artifact Registry - PRODUCTION (Production branch)

on:
  pull_request:
    types: [closed]
    branches:
      # This workflow has been disabled until approved by Admins
      - Disabled 
  push:
    branches:
      # This workflow has been disabled until approved by Admins
      - Disabled 
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'
    
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Information
      run: |
        echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    - name: Environment variables
      run: |
        echo "Your project id is ${{ env.GCP_PROJECT_ID }} and region is ${{ env.GCP_REGION }}."
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    
    - name: Check latest change in branch
      run: |
        git log -1

    - name: Authenticate to GCP using Workload Identity Federation
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/232450500396/locations/global/workloadIdentityPools/olenbeegithubpool/providers/olenbeegithubprovider'
        service_account: 'olenbee-deployment-pipeline@olb-beneficiaries-api-prd-6530.iam.gserviceaccount.com'

    - name: Login to GCR/AR
      run: |
        docker login europe-west9-docker.pkg.dev -u oauth2accesstoken -p $(gcloud auth print-access-token)
                
    - name: Image ID to compare in GCP artifact registry
      run: docker images   

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push image ${{ env.IMAGE_NAME }} using Buildx
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 --push \
          -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./

env:
  ENV: production  
  GCP_PROJECT_ID: olb-beneficiaries-api-prd-6530
  AR_URL: europe-west9-docker.pkg.dev/olb-beneficiaries-api-prd-6530/ms-appdata
  GCP_REGION: europe-west9
  SERVICE_NAME: ms-appdata
  IMAGE_NAME: ms-appdata